languages:
  JavaScript: true

exclude_paths:
    - "dist/*"
    - "build/*"
    - ".gen/*"
    - "mock/*"
    - "src/styles/*"
    - "src/js/*/__tests__"
    - "coverage/*"
    - "node_modules/*"
    - "Gruntfile.js"
